# This is an example of settings that can be used as a starting point for extractting 2D features from MR data 
# This is only intended as a starting point and is not likely to be the optimal settings for your dataset.
# Some points in determining better values are added as comments where appropriate

# When adapting and using these settings for an analysis, be sure to add the PyRadiomics version used to allow you to
# easily recreate your extraction at a later timepoint:

# #############################  Extracted using PyRadiomics version: <version>  ######################################

imageType:
  Original: {}

featureClass:
  firstorder:
     - 'Mean'
     - 'Minimum'
     - '90Percentile'
  shape2D:
     - 'Elongation'
     - 'Sphericity'
  glszm:
     - 'LargeAreaLowGrayLevelEmphasis'
     - 'SizeZoneNonUniformityNormalized'
  glcm:
     - 'Idmn'
  glrlm:
     - 'RunEntropy'

setting:
  # Normalization:
  #normalize: true
  #normalizeScale: 100

  # Misc:
  label: 255

